export const chatCategories = {
    diagnosisChat: [
        "Cough",
        "Fever",
        "Headache",
        "Sore throat",
        "Runny nose",
        "Muscle aches",
        "Fatigue",
        "Chills",
        "Nausea",
        "Body pain",
        "Shortness of breath",
        "Chest tightness",
        "Abdominal pain",
        "Diarrhea",
        "Vomiting",
        "Dizziness",
        "Swollen lymph nodes",
        "Rash",
        "Loss of appetite",
        "Night sweats"
    ],

    fitnessChat: [
        "Build muscle",
        "Lose weight",
        "Increase stamina",
        "Gain strength",
        "Improve flexibility",
        "Reduce pain",
        "Boost energy",
        "Fix posture",
        "Burn fat",
        "Recover faster",
        "Stay consistent",
        "Learn form",
        "Prevent injuries",
        "Reduce soreness",
        "Be active"
    ],

    dietChat: [
        "Eat healthy",
        "Lose weight",
        "Gain muscle",
        "Improve digestion",
        "Drink water",
        "Cut sugar",
        "Plan meals",
        "More protein",
        "Healthy snacks",
        "Portion control",
        "More energy",
        "Reduce bloating",
        "Better sleep",
        "Follow diet",
        "Save money"
    ]
};
